### ISSUE TITLE
calc_resistances function in TSEB.py

### ISSUE THREAD

**Issue by ClaireBrenner** [hectornieto/pyTSEB#11]
Hello,
I downloaded the updated version of pyTSEB and I think that there is an issue in the function calc_resistances. However, I am not totally sure. 

1) in line 2514 the variable should be named u_S instead of u_d_zm. Otherwise an error is raised if the condition massman_profile[0] == 0 is not true.

2) in general, I think massman_profile is missing in the docstring e.g. in TSEB_PT. It is thus difficult to say which values it could have exampt for the default. 

3) the if condition in line 2504 and 2551 have no effects (since in both cases the same function is called with the same arguments). Maybe this is only a placeholder by now.

**Comment by hectornieto** [comment]
Hi! Massman profile is not published yet so there is a "voluntary" bug

Cheers

Hector Nieto. Sent from my Android mobile... apologies for eventual typos

On Nov 3, 2017 18:58, ClaireBrenner <notifications@github.com> wrote:

Hello,
I downloaded the updated version of pyTSEB and I think that there is an issue in the function calc_resistances. However, I am not totally sure.

  1.  in line 2514 the variable should be names u_S instead of u_d_zm. Otherwise an error is raised if the condition massman_profile[0] == 0 is not true.

  2.  in general, I think massman_profile is missing in the docstring e.g. in TSEB_PT. It is thus difficult to say which values it could have exampt for the default.

  3.  the if condition in line 2504 and 2551 have no effects (since in both cases the same function is called with the same arguments). Maybe this is only a placeholder by now.

**Comment by radosuav** [comment]
Hi, as Hector said Massman profile is not published yet but when updating the code I was in a hurry and didn't remove all the references. I'll make a cleanup commit.
